In [3]:
# Import statements
import pandas as pd

In [11]:
#File locations
bac_meta = "../../r232/bac120_metadata_r232.tsv"
bac_tax = "../../r232/bac120_taxonomy_r232.tsv"
bac_tree = "../../r232/bac120_tree_r232.tsv"

archea_meta = "../../r232/ar53_metadata_r232.tsv"
archea_tax = "../../r232/ar53_taxonomy_r232.tsv"
archea_tree = "../../r232/ar53_tree_r232.tsv"

## Metadata table processing

In [14]:
bac_meta_df = pd.read_csv(bac_meta, sep="\t")
bac_meta_df["domain"] = "Bacteria"
archea_meta_df = pd.read_csv(archea_meta, sep="\t")
archea_meta_df["domain"] = "Archaea"
stacked_meta_df = pd.concat([bac_meta_df, archea_meta_df], axis=0)

stacked_meta_df

,accession,ambiguous_bases,checkm2_completeness,checkm2_contamination,checkm2_model,checkm_completeness,checkm_contamination,checkm_marker_count,checkm_marker_lineage,checkm_marker_set_count,...,ssu_silva_blast_bitscore,ssu_silva_blast_evalue,ssu_silva_blast_perc_identity,ssu_silva_blast_subject_id,ssu_silva_taxonomy,total_gap_length,trna_aa_count,trna_count,trna_selenocysteine_count,domain
0,RS_GCF_027889305.1,0,100.00,0.10,Specific,99.77,0.88,1173,f__Enterobacteriaceae (UID5124),336,...,2843,0,100,CP031565.2116397.2117948,Bacteria;Pseudomonadota;Gammaproteobacteria;En...,647,18,67,1,Bacteria
1,GB_GCA_947493065.1,0,88.72,3.56,General,87.89,4.99,230,k__Bacteria (UID2982),148,...,none,none,none,none,none,0,19,59,0,Bacteria
2,GB_GCA_949388335.1,0,99.64,0.61,Specific,97.30,0.50,406,o__Bacteroidales (UID2617),265,...,none,none,none,none,none,0,19,35,0,Bacteria
3,RS_GCF_029427315.1,0,100.00,0.22,Specific,99.70,0.48,1162,f__Enterobacteriaceae (UID5121),336,...,948,0,100,AJJI01000014.612023.613555,Bacteria;Pseudomonadota;Gammaproteobacteria;En...,0,19,85,1,Bacteria
4,RS_GCF_000217535.2,0,99.98,0.19,Specific,96.47,0.00,140,k__Bacteria (UID2495),85,...,2782,0,100,CP011410.3161998.3163511,Bacteria;Spirochaetota;Leptospirae;Leptospiral...,0,19,37,0,Bacteria
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22338,GB_GCA_964217815.1,0,72.41,0.89,Specific,78.63,0.00,188,p__Euryarchaeota (UID3),125,...,none,none,none,none,none,0,17,35,0,Archaea
22339,GB_GCA_964588555.1,0,92.48,1.72,General,91.82,2.80,149,k__Archaea (UID2),107,...,1035,0,88.439,HQ395738.1.1465,Archaea;Micrarchaeota;Micrarchaeia;Micrarchaea...,0,13,16,0,Archaea
22340,GB_GCA_038880715.1,0,98.95,0.65,General,96.26,1.87,149,k__Archaea (UID2),107,...,none,none,none,none,none,788,19,42,0,Archaea
22341,GB_GCA_041305945.1,0,63.56,2.43,General,66.00,2.34,149,k__Archaea (UID2),107,...,none,none,none,none,none,0,15,29,2,Archaea
22342,GB_GCA_022729255.1,0,91.38,0.06,General,80.37,0.47,149,k__Archaea (UID2),107,...,1378,0,85.262,KJ882189.1.1353,Archaea;Nanohaloarchaeota;Nanosalinia;Nanosali...,0,19,41,0,Archaea

In [19]:
## Unique accessions

print(f"Number of unique accessions: {stacked_meta_df['accession'].nunique()}")
print(f"Number of rows: {stacked_meta_df.shape[0]}")
print(f"is the number of unique accessions equal to the number of rows? {stacked_meta_df['accession'].nunique() == stacked_meta_df.shape[0]}")

Number of unique accessions: 901341
Number of rows: 901341
is the number of unique accessions equal to the number of rows? True

Make sense as the accession ID is effectively the index for the metadata tables.

## Taxonomy table

In [22]:
bac_tax_df = pd.read_csv(bac_tax, sep="\t", header=None)
bac_tax_df["domain"] = "Bacteria"
archea_tax_df = pd.read_csv(archea_tax, sep="\t", header=None)
archea_tax_df["domain"] = "Archaea"
stacked_tax_df = pd.concat([bac_tax_df, archea_tax_df], axis=0)
header = ["accession", "taxonomy", "domain"]
stacked_tax_df.columns = header

stacked_tax_df

,accession,taxonomy,domain
0,RS_GCF_051534235.1,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria
1,RS_GCF_046376025.1,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria
2,RS_GCF_021110035.1,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria
3,RS_GCF_030510125.1,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria
4,RS_GCF_037287565.1,d__Bacteria;p__Pseudomonadota;c__Gammaproteoba...,Bacteria
...,...,...,...
22338,GB_GCA_964649265.1,d__Archaea;p__Micrarchaeota;c__Micrarchaeia;o_...,Archaea
22339,GB_GCA_016839945.1,d__Archaea;p__Asgardarchaeota;c__Heimdallarcha...,Archaea
22340,GB_GCA_014523625.1,d__Archaea;p__Thermoproteota;c__Nitrososphaeri...,Archaea
22341,GB_GCA_002688395.1,d__Archaea;p__Nanobdellota;c__Nanobdellia;o__S...,Archaea
22342,RS_GCF_900104065.1,d__Archaea;p__Halobacteriota;c__Halobacteria;o...,Archaea

In [23]:
# accessions per taxa 

unique_taxa = stacked_tax_df["taxonomy"].nunique()
unique_accessions = stacked_tax_df["accession"].nunique()
print(f"Number of unique taxa: {unique_taxa}")
print(f"Number of unique accessions: {unique_accessions}")
print(f"Is the number of unique taxa equal to the number of unique accessions? {unique_taxa == unique_accessions}")

Number of unique taxa: 199923
Number of unique accessions: 901341
Is the number of unique taxa equal to the number of unique accessions? False

Some taxa must be represented by multiple species

In [26]:
accessions_per_taxa = stacked_tax_df.groupby("taxonomy")["accession"].nunique()

accessions_per_taxa.describe()

count    199923.000000
mean          4.508441
std         139.704724
min           1.000000
25%           1.000000
50%           1.000000
75%           2.000000
max       36408.000000
Name: accession, dtype: float64

Most species have 1 a few seem to have a lot

In [28]:
top_ten = accessions_per_taxa.sort_values(ascending=False).head(10)
top_ten

taxonomy
d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Escherichia;s__Escherichia coli        36408
d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Klebsiella;s__Klebsiella pneumoniae    28487
d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__Salmonella;s__Salmonella enterica      21527
d__Bacteria;p__Bacillota;c__Bacilli;o__Staphylococcales;f__Staphylococcaceae;g__Staphylococcus;s__Staphylococcus aureus                  19502
d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Enterobacterales;f__Enterobacteriaceae;g__ECMA0423;s__ECMA0423 sp047199055       13724
d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Pseudomonadales;f__Pseudomonadaceae;g__Pseudomonas;s__Pseudomonas aeruginosa     12456
d__Bacteria;p__Pseudomonadota;c__Gammaproteobacteria;o__Pseudomonadales;f__Moraxellaceae;g__Acinetobacter;s__Acinetobacter baumannii     11844
d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Streptococcaceae;g__Streptococcus;s__Streptococcus pneumoniae                   9634
d__Bacteria;p__Actinomycetota;c__Actinomycetes;o__Mycobacteriales;f__Mycobacteriaceae;g__Mycobacterium;s__Mycobacterium tuberculosis      7759
d__Bacteria;p__Bacillota;c__Bacilli;o__Lactobacillales;f__Enterococcaceae;g__Enterococcus;s__Enterococcus faecalis                        5041
Name: accession, dtype: int64

These seem to be the most common species.